# database
spring:
  datasource:
    url: jdbc:h2:mem:studybuddydb

#  datasource:
#    url: jdbc:mariadb://localhost:3306/studybuddydb?allowMultiQueries=true
#    username: admin
#    password: 1234

# jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

# logging
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
